export const tariffPlans = [
  {
    id: 1,
    titleMain: "Basic",
    subtitle: "TRY FOR FREE",
    ordersCount: "",
    content: ["1 User", "1 Order", "1 Product", "1Gb Storage"],
    plan: "BASIC",
    price: "FREE",
  },
  {
    id: 2,
    titleMain: "Business",
    subtitle: "125 CHF",
    ordersCount: "15 orders / 5 products",
    content: ["5 Users", "15 Orders", "15 Products", "5Gb Storage"],
    bonus: [
      "100 API calls free/month",
      "Limited analitics reports",
      "Email suport",
    ],
    plan: "BUSINESS",
    price: "$125",
  },
  {
    id: 3,
    titleMain: "ENTERPRISE",
    subtitle: "Custom / Tailored made",
    ordersCount: "UNLIMITED",
    content: ["Users", "Orders", "Products", "Storage"],
    bonus: [
      "1000 API calls free/month",
      "Customer support portal",
      "Premium listing",
      "ERP System Integration",
    ],
    plan: "ENTERPRISE",
    price: "CONTACT SALE",
  },
];
